spring.application.name=librarian
server.port=8080

spring.thymeleaf.cache=false

spring.data.mongodb.uri=${MONGODB_URI:mongodb://127.0.0.1:27017/librarian?serverSelectionTimeoutMS=5000}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${MAIL_FROM:no-reply@librarian.com.br}


server.error.include-message=always

logging.level.org.springframework.data.mongodb=INFO


spring.jackson.time-zone=America/Sao_Paulo